"""empty message

Revision ID: 40337834890f
Revises: abe03cd7bbc1
Create Date: 2019-03-13 23:10:18.124715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40337834890f'
down_revision = 'abe03cd7bbc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('cengine', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car', 'cengine')
    # ### end Alembic commands ###
