"""empty message

Revision ID: abe03cd7bbc1
Revises: f4ca828133a8
Create Date: 2019-03-13 23:01:00.949494

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'abe03cd7bbc1'
down_revision = 'f4ca828133a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car', 'cengine')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('cengine', mysql.VARCHAR(length=10), nullable=False))
    # ### end Alembic commands ###
