"""empty message

Revision ID: f4ca828133a8
Revises: d5b6c05d31fe
Create Date: 2019-03-13 23:00:32.314947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4ca828133a8'
down_revision = 'd5b6c05d31fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('cengine', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car', 'cengine')
    # ### end Alembic commands ###
